# Generated by Django 4.2.7 on 2023-11-07 13:45

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('name', models.CharField(max_length=100, verbose_name='Desciçao para SSL')),
                ('certificate', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/cosmeaf/Desktop/Projects/django/django_smartmecanico_v006/certs'), upload_to='tmp/')),
                ('private_key', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/cosmeaf/Desktop/Projects/django/django_smartmecanico_v006/certs'), upload_to='tmp/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
