# Generated by Django 4.2.7 on 2023-11-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_secure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sslcertificate',
            options={'verbose_name': 'Certificado SSL', 'verbose_name_plural': 'Certificados SSL'},
        ),
        migrations.AddIndex(
            model_name='sslcertificate',
            index=models.Index(fields=['name'], name='smart_secur_name_f6d6ec_idx'),
        ),
    ]
