# Generated by Django 4.2.7 on 2023-11-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_address'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['cep'], name='dashboard_a_cep_a3441b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='dashboard_c_email_b7c8a4_idx'),
        ),
    ]
