# Generated by Django 4.2.7 on 2023-11-05 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_address_dashboard_a_cep_a3441b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('fuel', models.CharField(max_length=50, verbose_name='Combustível')),
                ('year', models.CharField(max_length=4, verbose_name='Ano')),
                ('odometer', models.CharField(max_length=20, verbose_name='Hodometro')),
                ('plate', models.CharField(max_length=15, unique=True, verbose_name='Placa')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Chassi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-deleted_at', '-updated_at', 'year', 'brand', 'plate', 'vin'],
                'indexes': [models.Index(fields=['plate'], name='dashboard_v_plate_4d9f81_idx')],
            },
        ),
    ]
