# Generated by Django 4.2.7 on 2023-11-05 18:57

import dashboard.models.appointment_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_services_hourservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('time', models.CharField(help_text='Formato: 00:00', max_length=5, verbose_name='Hora do Serviço')),
                ('date', models.DateField(help_text='Formato: YYYY-MM-DD', verbose_name='Data do Serviço')),
                ('protocol', models.CharField(default=dashboard.models.appointment_model.generate_protocol, max_length=22, unique=True, verbose_name='Protocolo')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Justificativa para o cancelamento')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', related_query_name='schedule', to='dashboard.address', verbose_name='Endereço')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee', verbose_name='Mecânico')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', related_query_name='schedule', to='dashboard.services', verbose_name='Serviço')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', related_query_name='schedule', to='dashboard.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user'], name='dashboard_e_user_id_3839aa_idx'),
        ),
    ]
