# Generated by Django 4.2.7 on 2023-11-06 10:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0008_remove_purchase_item_delete_item_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('dtcs', models.JSONField(blank=True, null=True)),
                ('engine_rpm', models.IntegerField(blank=True, null=True)),
                ('vehicle_speed', models.IntegerField(blank=True, null=True)),
                ('coolant_temp', models.IntegerField(blank=True, null=True)),
                ('fuel_level', models.FloatField(blank=True, null=True)),
                ('throttle_position', models.FloatField(blank=True, null=True)),
                ('intake_air_temp', models.IntegerField(blank=True, null=True)),
                ('airflow_rate', models.FloatField(blank=True, null=True)),
                ('fuel_pressure', models.IntegerField(blank=True, null=True)),
                ('intake_manifold_pressure', models.IntegerField(blank=True, null=True)),
                ('timing_advance', models.FloatField(blank=True, null=True)),
                ('oxygen_sensors_voltage', models.JSONField(blank=True, null=True)),
                ('fuel_system_status', models.CharField(blank=True, max_length=100, null=True)),
                ('short_term_fuel_trim', models.FloatField(blank=True, null=True)),
                ('long_term_fuel_trim', models.FloatField(blank=True, null=True)),
                ('engine_load', models.FloatField(blank=True, null=True)),
                ('ambient_air_temp', models.IntegerField(blank=True, null=True)),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('error_count', models.IntegerField(blank=True, null=True)),
                ('driving_time_since_last_error', models.IntegerField(blank=True, null=True)),
                ('fuel_trim', models.FloatField(blank=True, null=True)),
                ('emission_requirements', models.CharField(blank=True, max_length=100, null=True)),
                ('oil_temperature', models.IntegerField(blank=True, null=True)),
                ('tire_pressure', models.JSONField(blank=True, null=True)),
                ('gear', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_data', to='dashboard.vehicle')),
            ],
            options={
                'verbose_name': 'Telemetria',
                'verbose_name_plural': 'Telemetrias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id'], name='telemetry_t_id_56459d_idx')],
            },
        ),
    ]
