# Generated by Django 4.2.7 on 2023-11-06 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_purchase_item_delete_item_delete_purchase'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vehicle')),
            ],
            options={
                'verbose_name': 'Localização do Veículo',
                'verbose_name_plural': 'Localizações dos Veículos',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['recorded_at'], name='telemetry_v_recorde_973544_idx'), models.Index(fields=['vehicle'], name='telemetry_v_vehicle_a21cd4_idx')],
            },
        ),
    ]
